name: Windows teste

on:
  push:
    tags:
      - "v*"

jobs:

  iniciar_windows:
    runs-on: ubuntu-latest

    steps:
      - name: Iniciando VM no Proxmox
        run: |
          curl -v -k -X POST \
            -H "Authorization: PVEAPIToken=${{ secrets.TOKEN_PROXMOX }}" \
            https://192.168.100.118:8006/api2/json/nodes/rhafa/qemu/101/status/start

  build:
    needs: iniciar_windows

    runs-on: windows

    defaults:
      run:
        shell: cmd

    steps: 
    
    - name: Atualizando repositório e limbando o build antigo
      shell: cmd
      run: |
        cd C:\gitea\Score-Maestro
        rd /s /q src-tauri\rclone
        git checkout .
        git pull
        rmdir /s /q src-tauri\target\x86_64-pc-windows-msvc\release\bundle\ || exit /b 0
      
    - name: Buildando o projeto em x64
      shell: cmd
      run: |
        cd C:\gitea\Score-Maestro
        npm run tauri:build:win:x64

    # - name: Mudando o nome do rclone
    #   shell: cmd
    #   run: |
    #     cd C:\gitea\Score-Maestro
    #     rem src-tauri\rclone\rclone.exe src-tauri\rclone\rclone64.exe 
    #     rem src-tauri\rclone\rclone32.exe src-tauri\rclone\rclone.exe 

    # - name: Buildando o projeto em x32
    #   shell: cmd
    #   run: |
    #     cd C:\gitea\Score-Maestro
    #     npm run tauri:build:win:x32

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Score-Maestro
        path: |
          C:\gitea\Score-Maestro\src-tauri\target\x86_64-pc-windows-msvc\release\bundle\*

    - name: Enviando aviso para o N8N
      run: |
        curl http://192.168.100.101:5678/webhook/9a1cb91d-299d-41d2-b6d6-5174134b7af9?project=ScoreMaestro


  finalizando_windows:
    if: always()

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Iniciando VM no Proxmox
        run: |
          curl -v -k -X POST \
            -H "Authorization: PVEAPIToken=${{ secrets.TOKEN_PROXMOX }}" \
            https://192.168.100.118:8006/api2/json/nodes/rhafa/qemu/101/status/shutdown